### ISSUE TITLE
Reconnect / offline

### ISSUE THREAD

**Issue by zooldk** [node-xmpp/core#89]
Hi Guys,

I've been experimenting a bit with this library and using it as a XMPP client.
I have experienced a lot of problems during disconnection of the networks.

E.g. when I disconnect I expect it to either give me an event "disconnect" or "offline" that I can react on. It does not happen when is do the disconnect.

I have also tried to enable reconnect - setting the reconnect = true on the options, that does not work either.

I have been using BOSH as transport and all my other clients (written in other languages) seems to be working - so it seems like a client implementation problem.

Basically I am trying to "catch" the disconnection with:

```
client.on('offline', function(data) {
    console.log('\n\n' + new Date() + ' offline. \n\n Data: ', data)
})

client.on('error', function(error) {
    console.log('\n\n' + new Date() + ' Error: ', error)
})

client.on('disconnect', function(e) {
    console.log('\n\n' + new Date() + ' Disconnect: ', e)  
})
```

I am using version 3.0.0 of node-xmpp-client.

-Cheers!

/Steffen

**Comment by sonnyp** [comment]
Hey

Sorry for the late reply. can you move this issue to node-xmpp-client?

**Comment by zooldk** [comment]
ok thanks . I have opened a new issue: https://github.com/node-xmpp/client/issues/199

**Comment by zooldk** [comment]
ok thanks . I have opened a new issue: https://github.com/node-xmpp/client/issues/199
